# Generated by Django 4.2.11 on 2025-05-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers_alter_user_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blood_group',
            field=models.CharField(choices=[('A_plus', 'A+'), ('A_minus', 'A-'), ('B_plus', 'B+'), ('B_minus', 'B-'), ('AB_plus', 'AB+'), ('AB_minus', 'AB-'), ('O_plus', 'O+'), ('O_minus', 'O-')], max_length=8),
        ),
    ]
